---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-service
  labels:
    app: weather-service-app
spec:
  template:
    metadata:
      name: weather-service-pod
      labels:
        app: weather-service-app
    spec:
      containers:
      - name: http
        image: weather-service:test
        imagePullPolicy: Never # Use locally built image
        env:
        - name: SENSE_BOX_IDS
          value: "5cf9874107460b001b828c5b,5ca4d598cbf9ae001a53051a,59f8af62356823000fcc460c"
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /temperature
            port: http
        livenessProbe:
          httpGet:
            path: /health
            port: http
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            memory: 100Mi
  selector:
    matchLabels:
      app: weather-service-app

