---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: weather-service
spec:
  maxReplicas: 3
  minReplicas: 1
  targetCPUUtilizationPercentage: 70
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: weather-service
